on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    env:
      build_path: 'C:\Users\SanifPC\Desktop\fb.apk'
      subscription_key: e570e948-0661-4481-8728-3b82ea0399a2

    steps:
      - id: foo
        uses: sanif8053/temp_action@master
        
