on: [push]
jobs:
  Uploading-job:  
    name: 'Upload build on Sofy'
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v2
      - name: 'Upload build' 
        env:
          build_path: 'fb.apk'
          subscription_key: c22e63fd-cd88-44b6-8593-be4f8586e958
        uses: 'SOFYAIOFFICIAL/sofy-upload-github-actions@main'
#         uses: 'sanif8053/temp_action@master'
